In [ ]:
import numpy as np

list = [1,2,3,4,5,6,7]
list_array = np.array(list)

print (list_array) #создаем массив из списка

[1 2 3 4 5 6 7]


In [ ]:
np.zeros((5,5)) #создаем массив из нулей размерности 5 на 5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,5)) #создаем массив из единиц размерности 5 на 5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arrayer = np.arange(1,30,2) #создаем массив чисел от 1 до 3 с шагом 2
print(arrayer)
print(arrayer.shape) #выводим на экран параметр shape
print(arrayer.dtype) #выводим на экран параметр dtype

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
(15,)
int64


In [ ]:
print(arrayer[7]) #выводим на экран элемент массива с индексом 7
print(arrayer[2:5]) #выводим на экран срез со 2 по 5 элемент

15
[5 7 9]


In [ ]:
array1 = np.array([1,3,5,7,9,11])
array2 = np.array([2,4,6,8,10,12])

print(array1 + array2) #выводим результат поэлементного сложения массивов
print(array1 * array2) #выводим результат умножения массивов
print(np.mean((array1+array2))) #выводим среднее значение результирующего массива суммы массивов


[ 3  7 11 15 19 23]
[  2  12  30  56  90 132]
13.0
